.TH MYSTRFUNCTIONS 3 "2025-09-21" "libmyutils" "User Contributed Functions"
.SH NAME
mystrlen, mystrcpy, mystrncpy, mystrcat \- basic string utilities
.SH SYNOPSIS
.B #include <mystrfunctions.h>
.br
.B int mystrlen(const char *s)
.br
.B int mystrcpy(char *dest, const char *src)
.br
.B int mystrncpy(char *dest, const char *src, int n)
.br
.B int mystrcat(char *dest, const char *src)
.SH DESCRIPTION
These functions provide simple string helpers. See include/mystrfunctions.h for details.
.SH AUTHOR
Your Name <your.email@example.com>

